owner: plibither8
repo: status.mhr.cx

sites:
  - name: mhr URL Shortener
    url: https://mhr.cx
  - name: Maloja
    url: https://maloja.mihir.ch
  - name: Git
    url: https://git.mihir.ch

status-website:
  cname: status.mhr.cx
  logoUrl: https://raw.githubusercontent.com/plibither8/plibither8/master/logo.svg
  name: Status @ mhr.cx
  introTitle: "Mihir's services' status page"
  introMessage: A status page for all my services hosted on my personal VPS. Getting too many downtimes recently :/.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Mihir
      href: https://mihir.ch

assignees:
  - plibither8

commitMessages:
  commitAuthorName: "plibother8"
  commitAuthorEmail: "bot@mihir.ch"
